services:
    Symfony\Contracts\HttpClient\HttpClientInterface $submissionImageClient: "@postmill.http_client.submission_images"

    postmill.http_client.submission_images:
        class: Symfony\Component\HttpClient\NoPrivateNetworkHttpClient
        arguments:
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'

framework:
    http_client:
        default_options:
            headers:
                User-Agent: "Postmill/%env(APP_VERSION)% (https://postmill.xyz)"
