submission:
    controller: App\Controller\SubmissionController::submission
    defaults: { slug: ~ }
    path: /{forum_name}/{submission_id}/{slug}
    methods: [GET]
    requirements: { submission_id: \d+ }

submission_shortcut:
    controller: App\Controller\SubmissionController::shortcut
    path: /{id}
    requirements: { id: \d+ }

comment:
    controller: App\Controller\SubmissionController::commentPermalink
    path: /{forum_name}/{submission_id}/comment/{comment_id}
    methods: [GET]

edit_submission:
    controller: App\Controller\SubmissionController::editSubmission
    path: /{forum_name}/edit_submission/{submission_id}
    methods: [GET, POST]

submission_delete_immediately:
    controller: App\Controller\SubmissionController::deleteImmediately
    path: /{forum_name}/delete_submission/{submission_id}
    methods: [POST]

submission_delete_with_reason:
    controller: App\Controller\SubmissionController::deleteWithReason
    path: /{forum_name}/delete_submission_with_reason/{submission_id}
    methods: [GET, POST]

lock:
    controller: App\Controller\SubmissionController::lock
    defaults: { lock: true }
    path: /{forum_name}/{submission_id}/lock
    methods: [POST]
    requirements: { id: \d+ }

unlock:
    controller: App\Controller\SubmissionController::lock
    defaults: { lock: false }
    path: /{forum_name}/{submission_id}/unlock
    methods: [POST]
    requirements: { id: \d+ }

submit:
    controller: App\Controller\SubmissionController::submit
    defaults: { forum_name: null }
    path: /submit/{forum_name}
    methods: [GET, POST]

submission_vote:
    controller: App\Controller\VoteController::vote
    defaults: { _format: html, entityClass: App\Entity\Submission }
    path: /sv/{id}.{_format}
    methods: [POST]
    requirements: { _format: html|json }
